# Generated by Django 5.2.7 on 2025-10-18 06:26

from django.db import IntegrityError, migrations, transaction
import os
import environ
import json

def populate_words(apps, schema_editor):
    word_file_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../gamepallets.json'))
    env = environ.Env()
    env.read_env(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../.env')))
    Pallet = apps.get_model('api', 'Pallet')
    Pallet.objects.all().delete()
    try:
        PalletArray = []
        with open(word_file_path, 'r') as f:
            pallets = json.load(f)
            for pallet in pallets:
                PalletArray.append(Pallet(name=pallet['name'], colors=pallet['codes']))
        with transaction.atomic():
            Pallet.objects.bulk_create(PalletArray)
    except IntegrityError:
        Pallet.objects.all().delete()
        


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RunSQL("UPDATE sqlite_sequence SET seq = 0 WHERE sqlite_sequence.name = 'api_pallet';"),
        migrations.RunPython(populate_words),
    ]
