# Generated by Django 5.2.7 on 2025-10-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_Populate_Pallets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guess',
            name='correct_count',
        ),
        migrations.AddField(
            model_name='guess',
            name='correct_bitmask',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
