# Generated by Django 5.2.7 on 2025-10-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_guess_correct_count_guess_correct_bitmask'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_nightmare',
            field=models.BooleanField(default=False),
        ),
    ]
