# Generated by Django 5.2.7 on 2025-10-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_guess_id_alter_guess_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('WON', 'Won'), ('LOST', 'Lost')], default='IN_PROGRESS', max_length=20),
        ),
    ]
