# Generated by Django 5.2.7 on 2025-10-18 06:26

from django.db import migrations
import os

word_file_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../words_alpha.txt'))
def populate_words(apps, schema_editor):
    Word = apps.get_model('api', 'Word')
    Word.objects.all().delete()
    WordArray = []
    with open(word_file_path, 'r') as f:
        words = f.read().splitlines()
        for word in words:
            if(len(word) == 5):
                WordArray.append(Word(value=word.upper()))
    Word.objects.bulk_create(WordArray)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_word_game_status'),
    ]

    operations = [
        migrations.RunPython(populate_words),
    ]
