# Generated by Django 5.2.7 on 2025-10-28 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_game_is_nightmare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_nightmare',
        ),
        migrations.CreateModel(
            name='NightmareGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('WON', 'Won'), ('LOST', 'Lost')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('challenge', models.CharField(choices=[('LIAR', 'The Liar'), ('BROKEN', 'The Broken Keyboard'), ('AMNESIA', 'The Amnesiac'), ('GLITCH', 'The Glitch'), ('VAMPIRE', 'The Vampire')], max_length=20)),
                ('challenge_value', models.CharField(default='', max_length=100)),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pallet')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NightmareGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=6)),
                ('correct_bitmask', models.CharField(default='0000', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color_feedback', models.JSONField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.nightmaregame')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
