# Generated by Django 5.2.7 on 2025-10-18 06:26

from django.db import migrations
import os
import environ

from Wordling.settings import BASE_DIR

word_file_path = os.path.join(BASE_DIR, 'api', 'words_alpha.txt')
def populate_words(apps, schema_editor):
    env = environ.Env()
    environ.Env.read_env(os.path.join(BASE_DIR, '.env'))
    Word = apps.get_model('api', 'Word')
    Word.objects.all().delete()
    WordArray = []
    with open(word_file_path, 'r') as f:
        words = f.read().splitlines()
        for word in words:
            if(len(word) == env('WORD_LENGTH')):
                WordArray.append(Word(value=word.upper()))
    Word.objects.bulk_create(WordArray)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_word_game_status'),
    ]

    operations = [
        migrations.RunSQL("UPDATE sqlite_sequence SET seq = 0 WHERE sqlite_sequence.name = 'api_word';"),
        migrations.RunPython(populate_words),
    ]
