# Generated by Django 5.2.7 on 2025-10-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_game_is_nightmare_nightmaregame_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guess',
            name='correct_bitmask',
        ),
        migrations.RemoveField(
            model_name='nightmareguess',
            name='correct_bitmask',
        ),
        migrations.AddField(
            model_name='game',
            name='correct_bitmask',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AddField(
            model_name='nightmaregame',
            name='correct_bitmask',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
