# Generated by Django 5.2.7 on 2025-10-18 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_Populate_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.word'),
        ),
    ]
