# Generated by Django 5.2.7 on 2025-10-19 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_guess_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.game'),
        ),
        migrations.AlterField(
            model_name='guess',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.word'),
        ),
    ]
