# Generated by Django 5.2.7 on 2025-10-19 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_guess_game_alter_guess_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='key',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('WON', 'Won'), ('LOST', 'Lost')], db_index=True, default='IN_PROGRESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
