# Generated by Django 5.2.7 on 2025-10-21 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_game_key_alter_game_status_alter_game_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game'),
        ),
        migrations.AlterField(
            model_name='guess',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.word'),
        ),
    ]
