import environ
import os

env = environ.Env()
env.read_env()

WORD_LENGTH = int(env('GAME_WORD_LENGTH', default=6))
MAX_GUESSES = int(env('GAME_MAX_GUESSES', default=9))

ANIMATION_SHAKE_MS = int(env('ANIMATION_SHAKE_MS', default=600))
ANIMATION_TILE_FLIP_STAGGER_MS = int(env('ANIMATION_TILE_FLIP_STAGGER_MS', default=100))
ANIMATION_BOUNCE_STAGGER_MS = int(env('ANIMATION_BOUNCE_STAGGER_MS', default=100))
ANIMATION_WIN_MODAL_DELAY_MS = int(env('ANIMATION_WIN_MODAL_DELAY_MS', default=1200))
ANIMATION_MODAL_DELAY_MS = int(env('ANIMATION_MODAL_DELAY_MS', default=200))
ANIMATION_TOAST_TIMEOUT_MS = int(env('ANIMATION_TOAST_TIMEOUT_MS', default=7000))

UI_TILE_GAP_PX = int(env('UI_TILE_GAP_PX', default=5))
UI_BOARD_MAX_WIDTH_PX = int(env('UI_BOARD_MAX_WIDTH_PX', default=350))
UI_BOARD_COLUMNS = int(env('UI_BOARD_COLUMNS', default=5))

LEADERBOARD_PAGE_SIZE = int(env('LEADERBOARD_PAGE_SIZE', default=50))

GUESS_DISTRIBUTION_SIZE = MAX_GUESSES

COLOR_CORRECT = 'G'      
COLOR_PRESENT = 'Y'      
COLOR_ABSENT = 'B'       
COLOR_BROKEN = 'S'  
COLOR_VAMPIRE_CORRECT = 'V'    
COLOR_VAMPIRE_PRESENT = 'M'    

WIN_PERCENTAGE_MULTIPLIER = 100


def get_game_constants():
    return {
        'WORD_LENGTH': WORD_LENGTH,
        'MAX_GUESSES': MAX_GUESSES,
        'WORD_LENGTH_RANGE': range(1, WORD_LENGTH + 1),
        'MAX_GUESSES_RANGE': range(1, MAX_GUESSES + 1),
        
        'ANIMATION_SHAKE_MS': ANIMATION_SHAKE_MS,
        'ANIMATION_TILE_FLIP_STAGGER_MS': ANIMATION_TILE_FLIP_STAGGER_MS,
        'ANIMATION_BOUNCE_STAGGER_MS': ANIMATION_BOUNCE_STAGGER_MS,
        'ANIMATION_WIN_MODAL_DELAY_MS': ANIMATION_WIN_MODAL_DELAY_MS,
        'ANIMATION_MODAL_DELAY_MS': ANIMATION_MODAL_DELAY_MS,
        'ANIMATION_TOAST_TIMEOUT_MS': ANIMATION_TOAST_TIMEOUT_MS,
        
        'UI_TILE_GAP_PX': UI_TILE_GAP_PX,
        'UI_BOARD_MAX_WIDTH_PX': UI_BOARD_MAX_WIDTH_PX,
        'UI_BOARD_COLUMNS': UI_BOARD_COLUMNS,
        
        'LEADERBOARD_PAGE_SIZE': LEADERBOARD_PAGE_SIZE,
    }
